### camelCase
---
apiVersion: postgres.krestomat.io/v1alpha1
kind: Postgres
metadata:
  name: readreplicas-sample
spec:
  # postgresMode: one of 'standalone', 'readreplicas'
  # by default 'standalone' is 1 one primary only, while 'readreplicas' is 1 primary and 1 replica
  postgresMode: 'readreplicas'
  postgresReadreplicasSize: 1

  # Autoexpansion: if storage available is less than 20% or 'postgresReadreplicasPvcDataAutoexpansionIncrementGib', adjust PVC storage size according to 'postgresReadreplicasPvcDataAutoexpansionIncrementGib' and 'postgresReadreplicasPvcDataAutoexpansionCapGib':
  # * Kubernetes cluster and PVC must support expansion of volumes
  # * In older cluster versions, pods require restart when autoexpanding if Kubernetes feature gate
  #   'ExpandInUsePersistentVolumes' is false. See:
  #   https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  ## Enable autoexpansion
  postgresReadreplicasPvcDataAutoexpansion: true
  ## Every time autoexpansion is required, increment 5 GiB
  postgresReadreplicasPvcDataAutoexpansionIncrementGib: 5
  ## But no more than 25 GiB
  postgresReadreplicasPvcDataAutoexpansionCapGib: 25

  # Add extra pgbouncer config
  pgbouncerExtraConfig: |
    listen_backlog = 256

  # Add extra pgbouncer config to readonly service
  pgbouncerReadonlyExtraConfig: |
    listen_backlog = 512
