### camelCase
---
apiVersion: postgres.krestomat.io/v1alpha1
kind: Postgres
metadata:
  name: postgres-sample
spec:
  # postgresMode: one of 'standalone', 'readreplicas'
  # by default 'standalone' is 1 one primary only, while 'readreplicas' is 1 primary and 1 replica
  postgresMode: 'standalone'

  # Assign 1Gi to each persistent volume: primary and replicas
  postgresPvcDataSize: 1Gi

  # Add extra pgbouncer config
  pgbouncerExtraConfig: |
    listen_backlog = 256
